---
# used for development/testing
version: '3'
services:
  aa_frontend:
    image: aa_frontend
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    command: bash -c "pwd && ls -al && npm run dev"
    ports:
      - 8080:8080
    environment:
      API_HOST: http://aa_client:8000
      APP_PORT: 8080
  aa_client:
    image: aa_client
    build:
      context: .
      dockerfile: docker/client.dockerfile
    command: bash -c "python3 /app/main.py"
    ports:
      - 8000:8888
    tty: true
    environment:
      APP_PORT: 8000
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}



